[build]
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/telegram"
  status = 200

[[redirects]]
  from = "/api/stock"
  to = "/.netlify/functions/api-stock"
  status = 200

[[redirects]]
  from = "/api/calibraciones"
  to = "/.netlify/functions/api-calibraciones"
  status = 200

[[redirects]]
  from = "/api/add-stock"
  to = "/.netlify/functions/api-add-stock"
  status = 200

[[redirects]]
  from = "/api/edit-stock"
  to = "/.netlify/functions/api-edit-stock"
  status = 200

[[redirects]]
  from = "/api/delete-stock"
  to = "/.netlify/functions/api-delete-stock"
  status = 200

[[redirects]]
  from = "/api/add-equipo"
  to = "/.netlify/functions/api-add-equipo"
  status = 200

[[redirects]]
  from = "/api/delete-equipo"
  to = "/.netlify/functions/api-delete-equipo"
  status = 200

[[redirects]]
  from = "/api/calibrar-equipo"
  to = "/.netlify/functions/api-calibrar-equipo"
  status = 200

[[redirects]]
  from = "/api/edit-equipo"
  to = "/.netlify/functions/api-edit-equipo"
  status = 200

[[redirects]]
  from = "/api/delete-stock-permanente"
  to = "/.netlify/functions/api-delete-stock-permanente"
  status = 200

[[redirects]]
  from = "/api/software"
  to = "/.netlify/functions/api-software"
  status = 200

[[redirects]]
  from = "/api/add-software"
  to = "/.netlify/functions/api-add-software"
  status = 200

[[redirects]]
  from = "/api/delete-software"
  to = "/.netlify/functions/api-delete-software"
  status = 200

[[redirects]]
  from = "/api/edit-software"
  to = "/.netlify/functions/api-edit-software"
  status = 200

[[redirects]]
  from = "/api/bancos"
  to = "/.netlify/functions/api-bancos"
  status = 200

[[redirects]]
  from = "/api/add-banco"
  to = "/.netlify/functions/api-add-banco"
  status = 200

[[redirects]]
  from = "/api/edit-banco"
  to = "/.netlify/functions/api-edit-banco"
  status = 200

[[redirects]]
  from = "/api/delete-banco"
  to = "/.netlify/functions/api-delete-banco"
  status = 200

[[redirects]]
  from = "/api/setups"
  to = "/.netlify/functions/api-setups"
  status = 200

[[redirects]]
  from = "/api/add-setup"
  to = "/.netlify/functions/api-add-setup"
  status = 200

[[redirects]]
  from = "/api/edit-setup"
  to = "/.netlify/functions/api-edit-setup"
  status = 200

[[redirects]]
  from = "/api/delete-setup"
  to = "/.netlify/functions/api-delete-setup"
  status = 200

[[redirects]]
  from = "/api/pasos"
  to = "/.netlify/functions/api-pasos"
  status = 200

[[redirects]]
  from = "/api/add-paso"
  to = "/.netlify/functions/api-add-paso"
  status = 200

[[redirects]]
  from = "/api/edit-paso"
  to = "/.netlify/functions/api-edit-paso"
  status = 200

[[redirects]]
  from = "/api/delete-paso"
  to = "/.netlify/functions/api-delete-paso"
  status = 200

[[redirects]]
  from = "/api/setup-software"
  to = "/.netlify/functions/api-setup-software"
  status = 200

[[redirects]]
  from = "/api/add-setup-software"
  to = "/.netlify/functions/api-add-setup-software"
  status = 200

[[redirects]]
  from = "/api/delete-setup-software"
  to = "/.netlify/functions/api-delete-setup-software"
  status = 200

[[redirects]]
  from = "/api/upload-foto-banco"
  to = "/.netlify/functions/api-upload-foto-banco"
  status = 200

[[redirects]]
  from = "/api/delete-foto-banco"
  to = "/.netlify/functions/api-delete-foto-banco"
  status = 200

[[redirects]]
  from = "/api/get-fotos-banco"
  to = "/.netlify/functions/api-get-fotos-banco"
  status = 200

[[redirects]]
  from = "/api/get-documentos-banco"
  to = "/.netlify/functions/api-get-documentos-banco"
  status = 200

[[redirects]]
  from = "/api/get-documentos-setup"
  to = "/.netlify/functions/api-get-documentos-setup"
  status = 200

[[redirects]]
  from = "/api/upload-documento-banco"
  to = "/.netlify/functions/api-upload-documento-banco"
  status = 200

[[redirects]]
  from = "/api/delete-documento-banco"
  to = "/.netlify/functions/api-delete-documento-banco"
  status = 200

[[redirects]]
  from = "/api/upload-documento-setup"
  to = "/.netlify/functions/api-upload-documento-setup"
  status = 200

[[redirects]]
  from = "/api/delete-documento-setup"
  to = "/.netlify/functions/api-delete-documento-setup"
  status = 200

[[redirects]]
  from = "/api/upload-foto-paso"
  to = "/.netlify/functions/api-upload-foto-paso"
  status = 200

[[redirects]]
  from = "/api/delete-foto-paso"
  to = "/.netlify/functions/api-delete-foto-paso"
  status = 200

[[redirects]]
  from = "/api/calibraciones-galgas"
  to = "/.netlify/functions/api-calibraciones-galgas"
  status = 200

[[redirects]]
  from = "/api/add-calibracion-galgas"
  to = "/.netlify/functions/api-add-calibracion-galgas"
  status = 200

[[redirects]]
  from = "/api/edit-calibracion-galgas"
  to = "/.netlify/functions/api-edit-calibracion-galgas"
  status = 200

[[redirects]]
  from = "/api/delete-calibracion-galgas"
  to = "/.netlify/functions/api-delete-calibracion-galgas"
  status = 200

[[redirects]]
  from = "/api/kanban-columnas"
  to = "/.netlify/functions/api-kanban-columnas"
  status = 200

[[redirects]]
  from = "/api/add-kanban-columna"
  to = "/.netlify/functions/api-add-kanban-columna"
  status = 200

[[redirects]]
  from = "/api/edit-kanban-columna"
  to = "/.netlify/functions/api-edit-kanban-columna"
  status = 200

[[redirects]]
  from = "/api/delete-kanban-columna"
  to = "/.netlify/functions/api-delete-kanban-columna"
  status = 200

[[redirects]]
  from = "/api/kanban-tarjetas"
  to = "/.netlify/functions/api-kanban-tarjetas"
  status = 200

[[redirects]]
  from = "/api/add-kanban-tarjeta"
  to = "/.netlify/functions/api-add-kanban-tarjeta"
  status = 200

[[redirects]]
  from = "/api/edit-kanban-tarjeta"
  to = "/.netlify/functions/api-edit-kanban-tarjeta"
  status = 200

[[redirects]]
  from = "/api/delete-kanban-tarjeta"
  to = "/.netlify/functions/api-delete-kanban-tarjeta"
  status = 200

[[redirects]]
  from = "/api/move-kanban-tarjeta"
  to = "/.netlify/functions/api-move-kanban-tarjeta"
  status = 200

[[redirects]]
  from = "/api/kanban-etiquetas"
  to = "/.netlify/functions/api-kanban-etiquetas"
  status = 200

[[redirects]]
  from = "/api/add-kanban-etiqueta"
  to = "/.netlify/functions/api-add-kanban-etiqueta"
  status = 200

[[redirects]]
  from = "/api/delete-kanban-etiqueta"
  to = "/.netlify/functions/api-delete-kanban-etiqueta"
  status = 200

[[redirects]]
  from = "/api/add-kanban-tarjeta-etiqueta"
  to = "/.netlify/functions/api-add-kanban-tarjeta-etiqueta"
  status = 200

[[redirects]]
  from = "/api/delete-kanban-tarjeta-etiqueta"
  to = "/.netlify/functions/api-delete-kanban-tarjeta-etiqueta"
  status = 200

[[redirects]]
  from = "/api/noticias"
  to = "/.netlify/functions/api-noticias"
  status = 200

[[redirects]]
  from = "/api/noticias-borradores"
  to = "/.netlify/functions/api-noticias-borradores"
  status = 200

[[redirects]]
  from = "/api/add-noticia"
  to = "/.netlify/functions/api-add-noticia"
  status = 200

[[redirects]]
  from = "/api/edit-noticia"
  to = "/.netlify/functions/api-edit-noticia"
  status = 200

[[redirects]]
  from = "/api/delete-noticia"
  to = "/.netlify/functions/api-delete-noticia"
  status = 200

[[redirects]]
  from = "/api/noticias-personas"
  to = "/.netlify/functions/api-noticias-personas"
  status = 200

[[redirects]]
  from = "/api/add-noticia-persona"
  to = "/.netlify/functions/api-add-noticia-persona"
  status = 200

[[redirects]]
  from = "/api/edit-noticia-persona"
  to = "/.netlify/functions/api-edit-noticia-persona"
  status = 200

[[redirects]]
  from = "/api/delete-noticia-persona"
  to = "/.netlify/functions/api-delete-noticia-persona"
  status = 200

[[redirects]]
  from = "/api/noticias-config"
  to = "/.netlify/functions/api-noticias-config"
  status = 200

[[redirects]]
  from = "/api/save-noticia-config"
  to = "/.netlify/functions/api-save-noticia-config"
  status = 200
